// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxsdmvlypsdaiykwlmuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4c2Rtdmx5cHNkYWl5a3dsbXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODg1MzYsImV4cCI6MjA2MDk2NDUzNn0.LKtDBEziHdOu6DUMHvcdCVXpo-XjHe_N6Q7G4GvY-Wc";

console.log('Initializing Supabase client...');
console.log('URL:', SUPABASE_URL);
console.log('Key:', SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

console.log('Supabase client initialized:', supabase);